# Generated by Django 3.1.4 on 2021-01-05 16:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('technical_specialist', models.CharField(blank=True, max_length=150)),
                ('estimated_elapsed_time', models.CharField(blank=True, max_length=100)),
                ('actual_time', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('finished', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.IntegerField(blank=True, default=0)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.project')),
            ],
        ),
    ]

